spring:
  rabbitmq:
    host: rabbit
  cloud:
    consul:
      host: consul
management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include:
          - bus-refresh
          - health
